### PR TITLE
added architecture requirements and one package

### PR DESCRIPTION
**Pull request by hirsche**
Hi Paolo,

I've changed the main.tex in order to include some new documents as a chapter (architecture). I used the same structure as you did!

But I created that pull request and didn't check it in directly to not confuse anybody.  So when ever you are ready kindly include the architecture part to the main. You could preview the document by compiling the latex file architecture-doc.tex in the same directory!

Best,
Eduard

### CODE REVIEW

**Comment by pdini** [comment]
Hi Eduard,

i am not sure I follow. Let me try asking some questions:

— Did you make the change in ShareLatex or locally on your machine?

— If you make a change you can commit and/or push, but you can’t pull. So what do you mean by ‘I created that pull request’?

Keep in mind that I am not an expert user of git, just a basic user. So if you give me some more explanation and simple instruction I may be able to help! :)

Best,
Paolo

**Comment by hirsche** [comment]
Dear Paolo,

> — Did you make the change in ShareLatex or locally on your machine?

I changed my stuff locally on my machine (I'm using Texmaker)

> — If you make a change you can commit and/or push, but you can’t pull. So
what do you mean by ‘I created that pull request’?


   - I could push/pull without any problem and I already pushed some parts to
   the git-repository which are independent of your files.
   - However, I also changed the file main.tex to include the architecture
   document I'm about to start. For that I created a new branch named
   *main-tex-change* (
   https://github.com/pdini/Interlace_D2.1/tree/main-tex-change)
   - I did this because I didn't want to confuse Egon or your ShareLatex
   process and wanted ask you first, if you want to include the architecture
   already into the document.
   - This is what I meant with "pull request" - I'm asking (with that pull
   request) if it is ok to merge my branch (main-tex-change) with the master
   branch. Which would be basically nothing else than confirming and adding my
   changes of "main.tex" to the common one (master branch)
   - ==> so on GitHub you would need to accept my changes and merge the
   branch main-tex-change and the master branch together.

If that doesn't make sense then you could just tell me if it is ok to add
the architecture part to the d2.1 document and I'll do it for you ;)

Best
Eduard



2017-07-21 15:03 GMT+02:00 pdini <notifications@github.com>:

> Hi Eduard,
>
> i am not sure I follow. Let me try asking some questions:
>
> — Did you make the change in ShareLatex or locally on your machine?
>
> — If you make a change you can commit and/or push, but you can’t pull. So
> what do you mean by ‘I created that pull request’?
>
> Keep in mind that I am not an expert user of git, just a basic user. So if
> you give me some more explanation and simple instruction I may be able to
> help! :)
>
> Best,
> Paolo
>
>
>

**Comment by hirsche** [comment]
two more things:


   - here you can see the changes:
   https://github.com/pdini/Interlace_D2.1/pull/1/files
   - and there (green button at the bottom: "merge pull request")
   https://github.com/pdini/Interlace_D2.1/pull/1 you could accept the
   changes.
   - of course you could also deny the request by using "close request" button

Eduard

2017-07-21 15:33 GMT+02:00 Eduard Hirsch <hirsch.eduard@gmail.com>:

> Dear Paolo,
>
> > — Did you make the change in ShareLatex or locally on your machine?
>
> I changed my stuff locally on my machine (I'm using Texmaker)
>
> > — If you make a change you can commit and/or push, but you can’t pull.
> So what do you mean by ‘I created that pull request’?
>
>
>    - I could push/pull without any problem and I already push some parts
>    to the git-repository which are independent of your files.
>    - However, I also changed the file main.tex to include the
>    architecture document I'm about to start. For that I created a new branch
>    named *main-tex-change* (https://github.com/pdini/
>    Interlace_D2.1/tree/main-tex-change
>    <https://github.com/pdini/Interlace_D2.1/tree/main-tex-change>)
>    - I did this because I didn't want to confuse Egon or your ShareLatex
>    process and wanted ask you first, if you want to include the architecture
>    already into the document.
>    - This is what I meant with "pull request" - I'm asking (with that
>    pull request) if it is ok to merge my branch (main-tex-change) with the
>    master branch. Which would be basically nothing else than confirming and
>    adding my changes of "main.tex" to the common one (master branch)
>    - ==> so on GitHub you would need to accept my changes and merge the
>    branch main-tex-change and the master branch together.
>
> If that doesn't make sense then you could just tell me if it is ok to add
> the architecture part to the d2.1 document and I'll do it for you ;)
>
> Best
> Eduard
>
>
>
> 2017-07-21 15:03 GMT+02:00 pdini <notifications@github.com>:
>
>> Hi Eduard,
>>
>> i am not sure I follow. Let me try asking some questions:
>>
>> — Did you make the change in ShareLatex or locally on your machine?
>>
>> — If you make a change you can commit and/or push, but you can’t pull. So
>> what do you mean by ‘I created that pull request’?
>>
>> Keep in mind that I am not an expert user of git, just a basic user. So
>> if you give me some more explanation and simple instruction I may be able
>> to help! :)
>>
>> Best,
>> Paolo
>>
>>
>>

**Comment by pdini** [comment]
Hi Eduard,

thanks for the extra explanations. I understand some of this, but not everything yet, sorry…

I pulled from my laptop and saw that a bunch of stuff was downloaded. I then compiled my local version and saw that the document did not change. This makes sense since you said that you made some changes but have not merged them yet and are waiting for me to approve them or for me to do the merge.

That’s great, but how can I approve something if I can’t see what it looks like? I am sure that it will be fine, but to be honest I would prefer to see what changes you made before merging. Is this possible? Am I being hopelessly obtuse?

Thank you for your patience.

Paolo

**Comment by hirsche** [comment]
Sure it should be exactly the way you described. I'm trying to clarify:

Short Explanation:

   - In your case you just need to call *"git checkout main-tex-change"* to
   see the most current state of the "main-tex-change"-branch (then recompile,
   check the pdf)
   - Finally call *"git checkout master"* to get back to the master branch

Note: Don't forget to checkout the master branch at the end. Otherwise you
would continue to add changes in the "main-tex-change".

Long Explanation

   - You are in the master-branch which is the main commit line. So
   currently if you pull the changes you receive all the most resent commits
   of that main branch (=master). Same with commit =>  so if you or anybody
   else commits, it is by default committed to the master branch.
   - I created a separate branch call "main-tex-change" to add a more or
   less critical change. This purposely does split of the master branch. Then
   I did change the new branch (commits and pushes) which does not have any
   influence on the master branch. I (and others) can commit and pull like in
   the master branch
   - From the splitting point the tex-sources certainly deviate
   - So consequently you have to decide in which branch you are working
   - you can do that in console by executing "git checkout <branchname>"
   - finally if you (or me in that case) decide that you are done with the
   changes, you can merge them together which basically means bringing the
   changes of the "main-tex-branch" to the master branch.

Hope that helps a little - if something is unclear I'm happy to assist
further. Anyway, that tutorial:

https://rogerdudler.github.io/git-guide/index.html

was really helpful for me. The branching is explained there as well.

Best,
Eduard


2017-07-21 18:56 GMT+02:00 pdini <notifications@github.com>:

> Hi Eduard,
>
> thanks for the extra explanations. I understand some of this, but not
> everything yet, sorry…
>
> I pulled from my laptop and saw that a bunch of stuff was downloaded. I
> then compiled my local version and saw that the document did not change.
> This makes sense since you said that you made some changes but have not
> merged them yet and are waiting for me to approve them or for me to do the
> merge.
>
> That’s great, but how can I approve something if I can’t see what it looks
> like? I am sure that it will be fine, but to be honest I would prefer to
> see what changes you made before merging. Is this possible? Am I being
> hopelessly obtuse?
>
> Thank you for your patience.
>
> Paolo
>
>
>
>

**Comment by pdini** [comment]
Thank you very much for the short and long explanations!

Wow, I am very impressed. I knew about branches but I had never used this feature. It’s very powerful! I followed exactly your commands and it worked! :)

So first a did git checkout main-tex-change and saw the rather large chapter you have added. Then i did git checkout master and verified that I got back to the original version. I have done nothing else so far.

Thank you for being so careful with the change management, it really helps. What I would like to do now is to alert the others that you have made these changes, after which I can do a merge and then pull the changes from ShareLatex.

At this point the next question will be whether Luca, Massi, Egon, and Giuseppe agree with (1) your terminology (chapter title) and structure; and (2) with the contents of the new chapter. I have no idea what they have in mind for this deliverable and for the architecture, so it will be interesting to see what they think.

Another point: Giuseppe and to some extent I are still thinking about the blockchain architecture. Is your chapter more of a “template” into which one can enter different types of architectural choices, technologies, etc? Or has it made some choices already regarding the blockchain? The high-level architectural choices for the blockchain will be made mainly be Giuseppe, with the rest of us supporting him.

I am officially on holiday from today, and am travelling to Italy tomorrow, but I always check my mail anyway and continue working at least a couple of hours a day. I might just be a bit slower in responding. On the 14th of August I fly from Tuscany to Sardinia and go back to a more regular working schedule. I am aiming to finalise and turn in this deliverable by end of August.

I will wait for your reply before I write to the others.

Thank you,
Paolo

**Comment by hirsche** [comment]
To be honest there isn't to much content in there yet, because we were
quite busy with administrational stuff. But Thomas and I planned to add an
approach from an software architectural point of view which should reflect
the high level architecture without any implementation details.

The document structure we suggest (in the tex-template) is a well know
approach provided by arc42 (http://arc42.org/). A guided version in tex can
be found here:

https://github.com/arc42/arc42-template/raw/master/dist/arc42-template-EN-
withhelp-latex.zip

The same version for Word (for quick viewing) can be found here:

https://github.com/arc42/arc42-template/raw/master/dist/arc42-template-EN-
withhelp-docx.zip

To answer your question about the content: No decisions  about the
blockchain or type have been made. It would be great if the architecture
could be made in a way that the type, brand or framework is not part of it
but rather a consequence. So I think it would be great if we define the top
level view in a way that we finally see which products are serving our
needs.

As soon as possible Thomas and me plan to send out an E-Mail to the others
as well. But I am in the same situation like you - I'm on vacation the next
week. Anyhow I try to do as much I can for the project.

Oh... what about the deadline of the D2.1, shouldn't it be ready at the end
of this month?

Anyhow, have a nice trip to Italy and enjoy your holidays!

All the best
Eduard


2017-07-21 21:13 GMT+02:00 pdini <notifications@github.com>:

> Thank you very much for the short and long explanations!
>
> Wow, I am very impressed. I knew about branches but I had never used this
> feature. It’s very powerful! I followed exactly your commands and it
> worked! :)
>
> So first a did git checkout main-tex-change and saw the rather large
> chapter you have added. Then i did git checkout master and verified that I
> got back to the original version. I have done nothing else so far.
>
> Thank you for being so careful with the change management, it really
> helps. What I would like to do now is to alert the others that you have
> made these changes, after which I can do a merge and then pull the changes
> from ShareLatex.
>
> At this point the next question will be whether Luca, Massi, Egon, and
> Giuseppe agree with (1) your terminology (chapter title) and structure; and
> (2) with the contents of the new chapter. I have no idea what they have in
> mind for this deliverable and for the architecture, so it will be
> interesting to see what they think.
>
> Another point: Giuseppe and to some extent I are still thinking about the
> blockchain architecture. Is your chapter more of a “template” into which
> one can enter different types of architectural choices, technologies, etc?
> Or has it made some choices already regarding the blockchain? The
> high-level architectural choices for the blockchain will be made mainly be
> Giuseppe, with the rest of us supporting him.
>
> I am officially on holiday from today, and am travelling to Italy
> tomorrow, but I always check my mail anyway and continue working at least a
> couple of hours a day. I might just be a bit slower in responding. On the
> 14th of August I fly from Tuscany to Sardinia and go back to a more regular
> working schedule. I am aiming to finalise and turn in this deliverable by
> end of August.
>
> I will wait for your reply before I write to the others.
>
> Thank you,
> Paolo
>
>
>

**Comment by pdini** [comment]
Hi Eduard,

the deadline for D2.1 is this month but I have already alerted the PO that it will be one month late, or possibly more if he wants us to include more details about the blockchain.

Better wait until the others see your high-level structure for the architecture chapter, before you and Thomas send an e-mail to everyone. I would rather check with each party individually first. It’s slower but safer this way, and in any case you are off next week so that’s perfect, it gives me a little time to bring the others up-to-date.

What you say about the design process sounds nice but I need to check with Egon that it is compatible with the ASMs and with Luca and Massi that they are OK with the approach.

I will send you updates as I get feedback from them and may merge your changes before you come back.

Thank you and have a nice holiday,

Paolo

**Comment by hirsche** [comment]
obsolete

**Pull request closed without merging**
